# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty
permalink:        :title/

# Setup
title:            Joaquim Ley
description:      'Hello I work as an Android Developer at Olx | Naspers. Besides coding, I <3 design, photography and playing the blues on the guitar.'
url:              http://joaquimley.com
baseurl:          /
logo:             /content/profile_pic.jpg

author:
  name:           'Joaquim Ley'
  url:            https://twitter.com/@JoaquimLey

paginate:         5

disqus_shortname: joaquimley

github:
  repo:           https://github.com/joaquimley/joaquimley.github.io

gems:
  - jekyll-sitemap

twitter: '@JoaquimLey'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM